export enum ElementsId {
  Name = 'name',
  Lastname = 'lastname',
  SignInButton = 'sign-in-button',
  ChatFormInput = 'chatFormInput',
  SearchInput = 'searchInput',
  ProfileName = 'profileName',
  AttachFilesModalInput = 'attachFilesModalInput',
  Img = 'img',
  LightBoxContainer = 'lightBoxContainer',
  Message = 'message',
  DocumentDataMessage = 'documentDataMessage',
  BottomItem = 'bottomItem',
  Scrollbars = 'scrollbars',
  Skeleton = 'skeleton',
  Select = 'select',
  NotSelect = 'not-select',
  Player = 'player',
  NotifyAudio = 'notifyAudio',
  LightThemeSwitcher = 'lightThemeSwitcher',
  DarkThemeSwitcher = 'darkThemeSwitcher',
}
