export enum ElementsId {
  Name = 'name',
  Lastname = 'lastname',
  SignInButton = 'sign-in-button',
  ChatFormInput = 'chatFormInput',
  SearchInput = 'searchInput',
  Img = 'img',
  LightBoxContainer = 'lightBoxContainer',
  Message = 'message',
  DocumentDataMsg = 'documentDataMsg',
  BottomItem = 'bottomItem',
  Scrollbars = 'scrollbars',
  Skeleton = 'skeleton',
  Select = 'select',
  NotSelect = 'not-select',
  Player = 'player',
  NotifyAudio = 'notifyAudio',
}
