export enum IconId {
  IconCrossClose = '#icon-cross-close',
  IconDeleteButton = '#icon-delete-button',
  IconPaperClip = '#icon-paper-clip',
  IconPhotoFocus = '#icon-photo-focus',
  IconRightArrow = '#icon-right-arrow',
  IconSendMessage = '#icon-send-message',
  IconTriangleRigth = '#icon-triangle-rigth',
  IconTriangleLeft = '#icon-triangle-left',
  IconMenu = '#icon-menu',
  IconSingleCheck = '#icon-single-check',
  IconDoubleCheck = '#icon-double-check',
  IconPencil = '#icon-pencil',
  IconEmoticon = '#icon-emoticon',
  IconCopy = '#icon-copy',
  IconStop = '#icon-stop',
  IconPlay = '#icon-play',
  IconMic = '#icon-mic',
  IconRec = '#icon-rec',
  IconScrollUp = '#icon-scroll-up',
  IconSearch = '#icon-search',
  IconSelect = '#icon-select',
  IconNotSelect = '#icon-not-select',
}
